#!/bin/bash

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
PROGNAME=$(basename $0)
if [ -z ${DATABASE} ]; then
	DATABASE=/var/data/substate_metrics.db
fi
# run sqlite3 command
#  $1: sqlite3 database filename
#  $2: sqlite3 commmand
function runsql () {
   sqlite3 $1 <<< "$2"
   if [ $? -ne 0 ]
   then
	echo "${PROGNAME}: sqlite3 failed executing $2 on db $1"
	exit 1
   fi
}

# check number of arguments
if [ "$#" -ne 1 ]; then
    echo "${PROGNAME}: specify log-file as single argument."
    exit 1
fi

# check whether log file exists
if [ ! -f "$1" ]; then
   echo "${PROGNAME}: logfile $1 does not exist."
   exit 1
fi


# make a temp file for converting log file to a csv file
TMP_FILE=$(mktemp -q /tmp/runtime.XXXXXX.csv || exit 1)

# set trap to clean up file
trap 'rm -f -- "$TMP_FILE"' EXIT

# Convert log output to a csv file
echo "${PROGNAME}: convert log-file to csv-file..."
grep "^metric" $1 | sed 's/^metric: //' > ${TMP_FILE}
# check whether file exists
if [ ! -f "${SCRIPTPATH}/storage_pre_4564036.csv" ]; then
   echo "${PROGNAME}: warning: storage_pre_4564036.csv does not exist. Output may be inaccurate!"
   echo "${PROGNAME}: the file is available at https://drive.google.com/drive/folders/1dHMbt6rpyoioYDdKKnslUyb2TS8JPT_k"
else
   cat ${SCRIPTPATH}/storage_pre_4564036.csv >> ${TMP_FILE}
fi

# Create sqlite3 table (drop old one)
echo "${PROGNAME}: create sqlite3 tables..."
runsql ${DATABASE} "CREATE TABLE IF NOT EXISTS experiment (type TEXT, creation_date TEXT, chainid TEXT, git_date TEXT, git_commit TEXT);"
runsql ${DATABASE} "DROP TABLE IF EXISTS storage_update;"
runsql ${DATABASE} "CREATE TABLE storage_update (
			block_number INTEGER NOT NULL,
			block_timestamp INTEGER NOT NULL,
			tx_number INTEGER NOT NULL,
			contract TEXT NOT NULL,
			storage_update_bytes INTEGER NOT NULL,
			input_update_bytes INTEGER NOT NULL,
			output_update_bytes TEXT NOT NULL,
			PRIMARY KEY (block_number, tx_number, contract));"

# Set experiment time
DATE=`date`
CHAIN_ID=`grep "^chain-id:" $1`
GIT_DATE=`grep "^git-date:" $1`
GIT_COMMIT=`grep "^git-commit:" $1`
runsql ${DATABASE} "INSERT INTO experiment VALUES (\"storage\",\"${DATE}\",\"${CHAIN_ID:9}\",\"${GIT_DATE:9}\",\"${GIT_COMMIT:11}\");"

# Load CSV file into sqlite3
echo "${PROGNAME}: import csv-file..."
runsql ${DATABASE} ".mode csv
.import ${TMP_FILE} storage_update"

echo "${PROGNAME}: compute storage size after each transaction..."
runsql ${DATABASE} "DROP TABLE IF EXISTS storage;"
runsql ${DATABASE} "CREATE TABLE storage AS
SELECT
	block_number,
	block_timestamp,
	tx_number,
	contract,
	SUM(storage_update_bytes) OVER (
		PARTITION BY contract
		ORDER BY block_number, tx_number
	)AS storage_bytes,
	storage_update_bytes,
	input_update_bytes,
	output_update_bytes
FROM storage_update;"

runsql ${DATABASE} "DROP TABLE IF EXISTS storage_update;"

# error check
echo "${PROGNAME}: find errors in storage table where storage size is smaller than substate update size..."
error_rows=`runsql ${DATABASE} "SELECT COUNT(*) FROM storage WHERE (storage_bytes - output_update_bytes) < 0 OR (storage_bytes - storage_update_bytes - input_update_bytes) < 0 limit 10;"`
echo "${PROGNAME}: ${error_rows} error entries found."

# views
echo "${PROGNAME}: create analytic tables..."
# account storage
runsql ${DATABASE} "DROP TABLE IF EXISTS max_contract_storage;"
runsql ${DATABASE} "CREATE TABLE max_contract_storage AS SELECT contract, MAX(storage_bytes) AS storage_bytes FROM storage GROUP BY contract;"

# transaction storage
runsql ${DATABASE} "DROP TABLE IF EXISTS transaction_storage;"
runsql ${DATABASE} "CREATE TABLE transaction_storage AS
SELECT
	block_number,
	block_timestamp,
	tx_number,
	SUM(storage_bytes) AS storage_bytes
FROM storage
GROUP BY block_number, block_timestamp, tx_number;"

# block storage
runsql ${DATABASE} "DROP TABLE IF EXISTS block_storage;"
runsql ${DATABASE} "CREATE TABLE block_storage AS
SELECT
	block_number,
	block_timestamp,
	SUM(storage_bytes) AS storage_bytes
FROM
	(SELECT
		block_number,
		block_timestamp,
		contract,
		MAX(storage_bytes) AS storage_bytes
	FROM storage
	GROUP BY block_number, block_timestamp)
GROUP BY block_number, block_timestamp;"

# blockchain storage
# sum of all contract storage
runsql ${DATABASE} "DROP TABLE IF EXISTS blockchain_storage;"
runsql ${DATABASE} "CREATE TABLE blockchain_storage AS SELECT SUM(storage_bytes) AS storage_bytes FROM max_contract_storage;"

#
# every 7 days (604800 seconds)
runsql ${DATABASE} "DROP TABLE IF EXISTS blockchain_storage_growth;"
runsql ${DATABASE} "CREATE TABLE blockchain_storage_growth AS
SELECT
	block_timestamp,
	SUM(storage_update_bytes) OVER (
		ORDER BY block_timestamp
	) AS storage_bytes
FROM
	(SELECT
		(block_timestamp / 604800) * 604800 AS block_timestamp,
		SUM(storage_update_bytes) AS storage_update_bytes
	FROM storage
	GROUP BY (block_timestamp / 604800) * 604800);
"
## update size per transaction
runsql ${DATABASE} "DROP TABLE IF EXISTS transaction_storage_updates"
runsql ${DATABASE} "CREATE TABLE transaction_storage_updates AS
SELECT block_number,
	tx_number,
	block_timestamp,
	sum(input_update_bytes) AS input_update_bytes,
	sum(output_update_bytes) AS output_update_bytes,
	sum(storage_update_bytes) storage_update_bytes
FROM storage
WHERE block_number > 4564035
GROUP BY block_number, tx_number;"

# remove temporary file
rm -f -- "$TMP_FILE"
trap - EXIT
exit
